-- MASTER TABLE 
CREATE TABLE SAHIL_MSTUSERPROFILE
(
  SYSUSERNO   NUMBER(10) PRIMARY KEY, -- PK OF MAIN TABLE
  USERID      VARCHAR2(50),
  FULLNAME    VARCHAR2(50),
  EMAIL       VARCHAR2(100),
  PASSWORD    VARCHAR2(100),
  AGE         VARCHAR2(50),
  PHONE       VARCHAR2(12),
  GENDER      VARCHAR2(50),
  ADDRESS     VARCHAR2(100),
  CITY        VARCHAR2(50),
  STATE       VARCHAR2(50),
  ZIPCODE     VARCHAR2(50),
  CREATEDBY   VARCHAR2(50),
  CREATEDDT   TIMESTAMP(3),
  LUPDNUSER   VARCHAR2(50),
  LUPDNDT     TIMESTAMP(3)
);
--DROP TABLE SAHIL_MSTUSERPROFILE;

-- TANSTABLE FOR MASTER
CREATE TABLE SAHIL_MSTUSERPROFILETRANS
(
  SYSTRNNO        NUMBER(22) PRIMARY KEY,  -- PK OF TRANS TABLE
  MSYSTRNNO       NUMBER(22),  -- WILL POINT TO THE PK OF TRANS TABLE ( USED TO TRANS MOTHER TRANSACTION)
  SYSUSERNO       NUMBER(10),  -- WILL POINT TO THE PK OF THE MAIN TABLE ( 0 WHEN RECORD IS INSERTED AND AND CHANGED AFTER AUTHRIZATION)
  TRNMODE         VARCHAR2(4), -- ADD OR EDIT
  TRNID           CHAR(1),     -- ALWAYS 'N' IN MAKER ADD RECORD TO THE TRANS ( ONLY AUTH SP CAN HAS POWER TO  ADD '0')
  TRNSTATUS       VARCHAR2(1), -- 'P' 'A' 'R' 
  CREATEDBY       VARCHAR2(50),
  CREATEDDT       TIMESTAMP(3),
  LUPDNUSER       VARCHAR2(50),
  LUPDNDT         TIMESTAMP(3),
  AUTHORISEDBY    VARCHAR2(50),
  AUTHORISEDON    TIMESTAMP(3),
  REJECTREMARK    VARCHAR2(500),-- IF REJECTED THEN REMARK
  
  
  USERID          VARCHAR2(50),
  FULLNAME        VARCHAR2(50),
  EMAIL           VARCHAR2(100),
  PASSWORD        VARCHAR2(100),
  AGE             VARCHAR2(50),
  PHONE           VARCHAR2(12),
  GENDER          VARCHAR2(50),
  ADDRESS         VARCHAR2(100),
  CITY            VARCHAR2(50),
  STATE           VARCHAR2(50),
  ZIPCODE         VARCHAR2(50)    
);
--DROP TABLE SAHIL_MSTUSERPROFILETRANS;

-- SP FOR MAIN TABLE SAHIL_MSTUSERPROFILE
CREATE SEQUENCE SAHIL_MSTUSERPROFILE_SEQ
START WITH 1 
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;
--DROP SEQUENCE SAHIL_MSTUSERPROFILE_SEQ;

-- SP FOR MAIN TABLE SAHIL_MSTUSERPROFILETRANS
CREATE SEQUENCE SAHIL_MSTUSERPROFILETRANS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;
--DROP SEQUENCE SAHIL_MSTUSERPROFILETRANS_SEQ;
