
SELECT * FROM USERS;
INSERT INTO USERS (
    SYSUSERNO,
    USERID,
    USERNAME,
    PASSWORD,
    LASTPASSWORDCHANGEDON,
    NEXTPASSWORDCHANGEDT,
    GROUPCODE,
    USERLEVEL,
    LOCATIONCD,
    EMAILID,
    PANNO,
    BIRTHDT,
    AUTHREJ,
    MULTILOGIN,
    LOGINSTATUS,
    USERSTATUS,
    LUPDNUSER,
    LUPDNDT,
    CREATEDBY,
    CREATEDDT,
    CLOSEDBY,
    CLOSEDDT,
    PASSWORDATTEMPT,
    LSTFAILEDLOGINDT,
    PREVLOGINDT,
    LASTLOGINDT,
    ADAUTH,
    MOBILENO_ENCRYPT,
    MOBILENO,
    EMAILID_ENCRYPT
)
VALUES (
    1204,
    'SAHIL.THALE',
    'SAHIL.THALE',
    '0F037584C99E7FD4F4F8C59550F8F507',
    TO_TIMESTAMP('23-09-25 12:09:16 PM', 'DD-MM-RR HH:MI:SS AM'),
    TO_TIMESTAMP('01-02-30 01:08:23 PM', 'DD-MM-RR HH:MI:SS AM'),
    'SAG',
    '01',
    1,
    'DONALDXXXXXXXXXX.COM',
    NULL,
    NULL,
    'N',
    'N',
    'N',
    '01',
    'DONALD',
    TO_TIMESTAMP('23-05-25 02:45:17 PM', 'DD-MM-RR HH:MI:SS AM'),
    'SAURABH',
    TO_TIMESTAMP('23-05-25 12:13:13 PM', 'DD-MM-RR HH:MI:SS AM'),
    NULL,
    NULL,
    4,
    NULL,
    TO_TIMESTAMP('24-12-25 03:41:17 PM', 'DD-MM-RR HH:MI:SS AM'),
    TO_TIMESTAMP('29-12-25 06:15:08 PM', 'DD-MM-RR HH:MI:SS AM'),
    'N',
    'ED4130886D0852490575910A3ABBF34F04B62C595B93A249BC5604EE6111799AC1EA97D4032A155EBDECE01C6AAC3032EA4499334D2B688C820DC0592154E112',
    'XXXXXXXXXX',
    'A456EC975AC3CB533308B34C0773C5BCF6B8D014EE9B30656B48F73E635CDB990B5EAB3018397FAC4A2EAB1FDB60FC12E0AFF97A4E4934D3439D3244D59F9F8E18F3EBAC412EB4C455C72CFCD533270B'
);
COMMIT;


SELECT * FROM USERGROUPS;
INSERT INTO USERGROUPS (
    SYSGROUPCODENO,
    GROUPCODE,
    DESCRIPTION,
    COMMENTS,
    MODULES,
    ISSUPERUSER,
    STATUS,
    CREATEDBY,
    CREATEDDT,
    LUPDNUSER,
    LUPDNDT
)
VALUES (
    843,
    'SAHIL',
    'SAHIL GROUP DEMO',
    'this group is same as group with SAG',
    'RBI RECON,09',
    'N',
    '01',
    'ADMIN',
    SYSDATE,
    'ADMIN',
    SYSDATE
);

UPDATE USERGROUPS SET  GROUPCODE='SAH' WHERE SYSGROUPCODENO=862;
COMMIT;



SELECT * FROM USERGROUPMODULES;
INSERT INTO USERGROUPMODULES (
    SYSGROUPNO,
    GROUPCODE,
    SHOWMODULEWISE,
    MODULES,
    CREATEDBY,
    CREATEDDT,
    LUPDNUSER,
    LUPDNDT,
    SYSGROUPCODENO
)
VALUES (
    303,
    'SAH',
    'Y',
    'IMPS,09',
    'ADMIN',
    SYSDATE,
    'ADMIN',
    TO_TIMESTAMP('08-01-19 12:00:00 AM', 'DD-MM-RR HH:MI:SS AM'),
    NULL
);

UPDATE USERGROUPMODULES SET MODULES='IMPS,09,SAHIL' WHERE SYSGROUPNO=303;

UPDATE USERS SET GROUPCODE='SAH' WHERE SYSUSERNO=1223;

COMMIT;



SELECT * FROM MODULES ORDER BY 1;
INSERT INTO MODULES(
MODULEID,
MODULENAME,
SITEURL,
MODULETYPE,
STATUS,
BUSINESSDT,
DAYBEGIN,
DAYEND,
DAYENDUSERID,
LAST7DAYSCBSCREATEDON,
FILEDATE,
COLORIMAGE,              
LINEIMAGE)
VALUES(
10,      
'SAHIL',  
NULL,   
NULL,
'A',  
SYSDATE,  
NULL,   
NULL   ,
NULL,       
SYSDATE,              
SYSDATE, 
'images/admin_color.png',
'assets/images/admin_line.png');
COMMIT;


SELECT * FROM RECOTYPES;
INSERT INTO RECOTYPES(
RECOTYPECD,
MODULECD,
DESCRIPTION,
CURRCD,
CBSFILEDAYS,
CLOSUREREMARKS,
RECORDSTATUS,
CREATEDBY,
CREATEDDT,
COLORIMAGE,              
LINEIMAGE,                
SITEURL,
ALLOW_ADJUSTMENT_YN,
DUPLICATE_DIRECTORY,
NOMATCH_DIRECTORY,
BAD_DIRECTORY,
SUCCESS_DIRECTORY,
FILELIST_DIRECTORY,
INBOUND_DIRECTORY,  
DBUPLOAD_DIRECTORY,    
LISTFILENAME,   
LISTFILERENAME, 
WINDOWSFILEPATH,                                                      
LUPDNUSER,LUPDNDT, 
PARENT_RECOTYPECD,
CONSIDER_COMMON,
ISESB)
VALUES(
'SAHIL',   
01,      
'SAHIL',   
NULL,  
NULL,       
NULL,          
01,          
'SAHIL',    
SYSDATE, 
'assets/images/recon.png',
'assets/images/recon.png',
NULL,   NULL,               
'DYNREC_DUPLICATE', 
'DYNREC_NOMATCH', 
'DYNREC_BAD', 
'DYNREC_SUCCESS', 
'FILELIST',        
'EMBER_3WAY_UPLOAD',
'EMBER_3WAY_DBUPLOAD', 
'FILELIST.TXT', 
'FILELIST.TXT', 
'\\mukut\Ember MatchPoint 3Way Recon\EMBER_3_WAY_RECON_UPLOAD\UPLOAD',
'ADMIN1',
SYSDATE, 
NULL,              
'Y',            
'N');
COMMIT;
