-- MAKER SP FOR TRANS TABLE SAHIL_MSTUSERPROFILETRANS
CREATE OR REPLACE PROCEDURE SAHIL_USP_SAVE_USERPROFILE
(
  P_SYSTRANNO   IN NUMBER,        -- IF 0 THEN ADD OR ELSE CHECK IF RECORD IS PENDING
  P_TRNMODE     IN VARCHAR2,      -- ADD / EDIT
  P_SYSUSERNO   IN NUMBER,        -- USED TO LINK TO MASTER TABLE DURING EDIT
  
  P_USERID      IN VARCHAR2,      -- USER FIELDS START
  P_FULLNAME    IN VARCHAR2,      
  P_EMAIL       IN VARCHAR2,
  P_PASSWORD    IN VARCHAR2,
  P_AGE         IN VARCHAR2,
  P_PHONE       IN VARCHAR2,
  P_GENDER      IN VARCHAR2,
  P_ADDRESS     IN VARCHAR2,
  P_CITY        IN VARCHAR2,
  P_STATE       IN VARCHAR2,
  P_ZIPCODE     IN VARCHAR2,      -- USER FIELDS END
  
  P_CREATEDBY   IN VARCHAR2,      -- MAKER ID
  P_CUROUTPUT   OUT SYS_REFCURSOR -- SYSTEM OUTPUT CURSOR
)
AS
  V_CNT         NUMBER := 0;      -- FOR VALIDATION CHECKS
  V_SEQUENCE    NUMBER;           -- TO HOLD THE NEXT TRANSACTION ID
  V_TRNSTATUS   VARCHAR2(10);     -- TO CHECK CURRENT STATUS ('P', 'A', etc.)
BEGIN


  -- 1. MASTER TABLE DUPLICATION CHECK (ONLY FOR 'ADD' MODE)

  -- We only check if the USERID exists in Master if we are trying to ADD a new user.
  -- If we are EDITING, the user already exists in Master, so we skip this check.
  IF P_TRNMODE = 'ADD' THEN
      SELECT COUNT(*) 
      INTO V_CNT
      FROM SAHIL_MSTUSERPROFILE
      WHERE USERID = P_USERID;

      IF V_CNT > 0 THEN
          OPEN P_CUROUTPUT FOR
          SELECT '0' AS FLAG, 'USER WITH THAT ID ALREADY PRESENT IN MASTER' AS MSG FROM DUAL;
          RETURN;
      END IF;
  END IF;

 
  -- 2. FETCH NEXT SEQUENCE VALUE FOR TRANSACTION TABLE

  V_SEQUENCE := SAHIL_MSTUSERPROFILETRANS_SEQ.NEXTVAL;


  -- 3. LOGIC FOR 'ADD' MODE
  
  IF P_TRNMODE = 'ADD' THEN
      -- Check if there is already a PENDING request for this same UserID
      SELECT COUNT(*) 
      INTO V_CNT
      FROM SAHIL_MSTUSERPROFILETRANS
      WHERE USERID = P_USERID AND TRNSTATUS = 'P';

      IF V_CNT > 0 THEN
          OPEN P_CUROUTPUT FOR
          SELECT '0' AS FLAG, 'A PENDING REQUEST FOR THIS USER ALREADY EXISTS' AS MSG FROM DUAL;
          RETURN; 
      ELSE
          INSERT INTO SAHIL_MSTUSERPROFILETRANS (
              SYSTRNNO, MSYSTRNNO, SYSUSERNO, TRNID, TRNMODE, TRNSTATUS, 
              CREATEDBY, CREATEDDT, USERID, FULLNAME, EMAIL, PASSWORD, 
              AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE
          )
          VALUES (
              V_SEQUENCE, 0, 0, 'N', P_TRNMODE, 'P', 
              P_CREATEDBY, CURRENT_TIMESTAMP, P_USERID, P_FULLNAME, P_EMAIL, P_PASSWORD, 
              P_AGE, P_PHONE, P_GENDER, P_ADDRESS, P_CITY, P_STATE, P_ZIPCODE
          );

          OPEN P_CUROUTPUT FOR
          SELECT '1' AS FLAG, 'RECORD SAVED SUCCESSFULLY (PENDING APPROVAL)' AS MSG FROM DUAL;
      END IF;


  -- 4. LOGIC FOR 'EDIT' MODE

  ELSIF P_TRNMODE = 'EDIT' THEN
      
      -- CASE A: UPDATING AN EXISTING PENDING TRANSACTION (P_SYSTRANNO is provided)
      IF NVL(P_SYSTRANNO, 0) != 0 THEN 
          SELECT TRNSTATUS INTO V_TRNSTATUS 
          FROM SAHIL_MSTUSERPROFILETRANS WHERE SYSTRNNO = P_SYSTRANNO;
          
          IF V_TRNSTATUS = 'P' THEN
              UPDATE SAHIL_MSTUSERPROFILETRANS
              SET USERID    = P_USERID, 
                  FULLNAME  = P_FULLNAME, 
                  EMAIL     = P_EMAIL,
                  PASSWORD  = P_PASSWORD,
                  AGE       = P_AGE,
                  PHONE     = P_PHONE,
                  GENDER    = P_GENDER,
                  ADDRESS   = P_ADDRESS,
                  CITY      = P_CITY,
                  STATE     = P_STATE,
                  ZIPCODE   = P_ZIPCODE,
                  CREATEDBY = P_CREATEDBY,
                  CREATEDDT = CURRENT_TIMESTAMP
              WHERE SYSTRNNO = P_SYSTRANNO;

              OPEN P_CUROUTPUT FOR
              SELECT '1' AS FLAG, 'PENDING RECORD UPDATED SUCCESSFULLY' AS MSG FROM DUAL;
              RETURN;
          
          -- CASE B: IF THE RECORD WAS ALREADY AUTHORIZED, CREATE A NEW PENDING EDIT REQUEST
          ELSIF V_TRNSTATUS = 'A' THEN
              INSERT INTO SAHIL_MSTUSERPROFILETRANS (
                  SYSTRNNO, MSYSTRNNO, SYSUSERNO, TRNID, TRNMODE, TRNSTATUS, 
                  CREATEDBY, CREATEDDT, USERID, FULLNAME, EMAIL, PASSWORD, 
                  AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE
              )
              VALUES (
                  V_SEQUENCE, P_SYSTRANNO, P_SYSUSERNO, 'N', P_TRNMODE, 'P', 
                  P_CREATEDBY, CURRENT_TIMESTAMP, P_USERID, P_FULLNAME, P_EMAIL, P_PASSWORD, 
                  P_AGE, P_PHONE, P_GENDER, P_ADDRESS, P_CITY, P_STATE, P_ZIPCODE
              );

              OPEN P_CUROUTPUT FOR
              SELECT '1' AS FLAG, 'NEW EDIT REQUEST SUBMITTED FOR APPROVAL' AS MSG FROM DUAL;
          END IF;

      -- CASE C: CREATING A NEW EDIT REQUEST FROM THE MASTER RECORD (P_SYSUSERNO is provided)
      ELSIF NVL(P_SYSUSERNO, 0) != 0 THEN
       -- ONE MORE LOGIC HERE  TO ADD TO CHECK IF THE MAIN TABLE RECORD EXIT OR NOT IF NOT THEN PROPER ERROR MESSAGE 
          SELECT COUNT(1)
          INTO V_CNT 
          FROM SAHIL_MSTUSERPROFILE
          WHERE SYSUSERNO=P_SYSUSERNO;
          
          IF V_CNT >0 THEN

          INSERT INTO SAHIL_MSTUSERPROFILETRANS (
              SYSTRNNO, MSYSTRNNO, SYSUSERNO, TRNID, TRNMODE, TRNSTATUS, 
              CREATEDBY, CREATEDDT, USERID, FULLNAME, EMAIL, PASSWORD, 
              AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE
          )
          VALUES (
              V_SEQUENCE, 0, P_SYSUSERNO, 'N', P_TRNMODE, 'P', 
              P_CREATEDBY, CURRENT_TIMESTAMP, P_USERID, P_FULLNAME, P_EMAIL, P_PASSWORD, 
              P_AGE, P_PHONE, P_GENDER, P_ADDRESS, P_CITY, P_STATE, P_ZIPCODE
          );

          OPEN P_CUROUTPUT FOR
          SELECT '1' AS FLAG, 'EDIT REQUEST SUBMITTED SUCCESSFULLY' AS MSG FROM DUAL;
          
          ELSE 
          OPEN P_CUROUTPUT FOR
          SELECT '0' AS FLAG, 'USER WITH THAT RECORD IS NOT EXIST ' AS MSG FROM DUAL;
          END IF;

      ELSE
          OPEN P_CUROUTPUT FOR
          SELECT '0' AS FLAG, 'PLEASE SPECIFY THE RECORD ID YOU WANT TO EDIT' AS MSG FROM DUAL;
          RETURN;
      END IF;


  -- 5. ERROR HANDLING FOR INVALID MODES

  ELSE
      OPEN P_CUROUTPUT FOR
      SELECT '0' AS FLAG, 'NOT A VALID OPERATION MODE (USE ADD OR EDIT)' AS MSG FROM DUAL;
      RETURN;
  END IF;

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
      ROLLBACK;
      OPEN P_CUROUTPUT FOR
      SELECT '0' AS FLAG, 'SYSTEM ERROR: ' AS MSG FROM DUAL;
END;
/





































-- AUTH (CHECKER SP) FOR MAIN TABLE SAHIL_MSTUSERPROFILE
CREATE OR REPLACE PROCEDURE SAHIL_USP_AUTHORISE_USERPROFILE
(
  P_SYSTRNNO     IN NUMBER,
  P_TRNSTATUS    IN VARCHAR2,   
  P_REJECTREMARK      IN VARCHAR2,
  P_AUTHORISEDBY      IN VARCHAR2,
  P_CUROUTPUT    OUT SYS_REFCURSOR
)
AS
  V_CNT       VARCHAR:=0;
  V_TRNMODE    VARCHAR2(4);
  V_SYSUSERNO  NUMBER;
  V_CREATEDBY  VARCHAR2(50);
BEGIN
  -- CHECKING IF RECORD EXIST OR NOT 
  
  SELECT COUNT(*)
  INTO V_CNT
  FROM SAHIL_MSTUSERPROFILE
  WHERE SYSTRNNO=P_SYSTRNNO;
-- THE RECORD SHOULD AT LEAST EXIST;
  IF V_CNT =0 THEN
  OPEN P_CUROUTPUT FOR
  SELECT '0' AS FLAG , ' NOT RECORD FOUNT TO AUTHORISE IN TRANS TABLE' AS MSG FROM DUAL;
  RETURN;
  END IF;
  
--  MAKER AND CHECK SHOULD NOT BE SAME EXCEPTION(ADMIN)
-- TRIAL PART LIKE IF ADMIN IN SENDING THE REQUEST THAT TIME WE MIGHT NEED THIS  
  IF V_MV_CREATEDBYAKER = P_AUTHORISEDBY THEN
    OPEN P_CUROUTPUT FOR
    SELECT '0' FLAG, 'Maker CAN NOT APROVE HIS OWN REQUEST' MSG FROM DUAL;
    RETURN;
  END IF;
  

  SELECT TRNMODE, SYSUSERNO, CREATEDBY
  INTO V_TRNMODE, V_SYSUSERNO, V_CREATEDBY
  FROM SAHIL_MSTUSERPROFILETRANS
  WHERE SYSTRNNO = P_SYSTRNNO
  AND TRNID = 'N'
  AND TRNSTATUS = 'P';




-- IF  REJECT

  IF P_TRNSTATUS = 'R' THEN
   IF P_REJECTREMARK !=NULL THEN
   
    UPDATE SAHIL_MSTUSERPROFILETRANS
    SET TRNSTATUS = 'R',
        REJECTREMARK = P_REJECTREMARK,
        AUTHORISEDBY = P_CHECP_AUTHORISEDBYKER,
        AUTHORISEDON = SYSDATE
    WHERE SYSTRNNO = P_SYSTRNNO
       OR MSYSTRNNO = P_SYSTRNNO;

    OPEN P_CUROUTPUT FOR
    SELECT '1' FLAG, 'Request rejected' MSG FROM DUAL;
    RETURN;
  ELSE
      OPEN P_CUROUTPUT FOR
    SELECT '0' FLAG, 'PLEASE PROVIDE THE REJECTION REASON' MSG FROM DUAL;
    RETURN;
  END IF;
  
  END IF;
--IF APPROVED
  
  IF V_TRNMODE = 'ADD' THEN
    INSERT INTO SAHIL_MSTUSERPROFILE
    SELECT
      SAHIL_MSTUSERPROFILE_SEQ.NEXTVAL,
      USERID, FULLNAME, EMAIL, PASSWORD,
      AGE, PHONE, GENDER, ADDRESS,
      CITY, STATE, ZIPCODE,
      CREATEDBY,
      CREATEDDT,
      NULL, -- LUPNDUSER
      NULL, -- LUPNDDT
      'A'
    FROM SAHIL_MSTUSERPROFILETRANS
    WHERE SYSTRNNO = P_SYSTRNNO;

    UPDATE SAHIL_MSTUSERPROFILETRANS
    SET SYSUSERNO = SAHIL_MSTUSERPROFILE_SEQ.CURRVAL;
  END IF;


  IF V_TRNMODE = 'EDIT' THEN
    UPDATE SAHIL_MSTUSERPROFILE M
    SET (USERID, FULLNAME, EMAIL, PASSWORD,
         AGE, PHONE, GENDER, ADDRESS,
         CITY, STATE, ZIPCODE,
         LUPDNUSER, LUPDNDT) =
        (SELECT USERID, FULLNAME, EMAIL, PASSWORD,
                AGE, PHONE, GENDER, ADDRESS,
                CITY, STATE, ZIPCODE,
                P_CHECKER, SYSDATE
         FROM SAHIL_MSTUSERPROFILETRANS
         WHERE SYSTRNNO = P_SYSTRNNO)
    WHERE SYSUSERNO = V_SYSUSERNO;
  END IF;


  UPDATE SAHIL_MSTUSERPROFILETRANS
  SET TRNSTATUS = 'A',
      AUTHORISEDBY = P_CHECKER,
      AUTHORISEDON = SYSDATE
  WHERE SYSTRNNO = P_SYSTRNNO
     OR MSYSTRNNO = P_SYSTRNNO;

  OPEN P_CUROUTPUT FOR
  SELECT '1' FLAG, 'Request approved successfully' MSG FROM DUAL;
  COMMIT;
END;

/
