-- MAKER SP FOR TRANS TABLE SAHIL_MSTUSERPROFILETRANS
-- OBSERVATIONS
--1. IF THE DATA IS GETTING FROM MAIN TABLE THAT TIME ONLY THE TRAN MODE WILL BE EDIT AND THAT TIME WE WILL USE P_SYSUSERNO

--2. IF THE DATA IN GETTING INTO TRANS THAT TIME THE TRNMODE WILL BE ADD ALWAYS AND WITH TRNSTATUS WILL BE 'N' 
--IF THE DATA IS GETTING INTO ADD THEN CHECK FOR IF THE SYSTRNNO IS THERE OR NOT IF YES THEN UPDATE OR ELSE
--CHECK THE DATA IN PRESENT IN THE MAIN TABLE OR TRANS TABLE IF YES THEN RESTURN ERROR MESSAGE OR ELSE
--INSERT INTO THE TRANSTABLE

--3. ADD LPNDUSER AND LPNDUSERAT IN TRANSTBALE ALSO
--
--4.ADD LOGIC IN AUTH SP ALSO ONLY SELECT RECORD WHOS TRANSSTATUS IS PENDING.
--
--5. DONT MAKE SP COMPLICATED

--6. CREATED BY AND CREATED AT NEVER CHANGES;

CREATE OR REPLACE PROCEDURE SAHIL_USP_SAVE_USERPROFILE
(
  P_SYSTRNNO    IN NUMBER,        -- 0 for new, or specific ID for updating pending record
  P_TRNMODE     IN VARCHAR2,      -- ADD / EDIT
  P_SYSUSERNO   IN NUMBER,        -- Links to Master table during EDIT
  P_USERID      IN VARCHAR2,
  P_FULLNAME    IN VARCHAR2,      
  P_EMAIL       IN VARCHAR2,
  P_PASSWORD    IN VARCHAR2,
  P_AGE         IN VARCHAR2,
  P_PHONE       IN VARCHAR2,
  P_GENDER      IN VARCHAR2,
  P_ADDRESS     IN VARCHAR2,
  P_CITY        IN VARCHAR2,
  P_STATE       IN VARCHAR2,
  P_ZIPCODE     IN VARCHAR2,
  P_CREATEDBY   IN VARCHAR2,      -- Maker ID
  P_CUROUTPUT   OUT SYS_REFCURSOR 
)
AS
  V_CNT         NUMBER := 0;
  V_SEQUENCE    NUMBER;
  V_TRNSTATUS   VARCHAR2(10);
BEGIN

  -- 1. PRE-VALIDATION: Check Main Table for duplicates (ID or Email)
  -- If EDIT mode, we exclude the current user's own record from the check
  SELECT COUNT(*) INTO V_CNT
  FROM SAHIL_MSTUSERPROFILE
  WHERE (USERID = P_USERID OR EMAIL = P_EMAIL)
    AND (P_TRNMODE = 'ADD' OR SYSUSERNO != P_SYSUSERNO);

  IF V_CNT > 0 THEN
    OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'User ID or Email already exists in Master record.' AS MSG FROM DUAL;
    RETURN;
  END IF;

  -- 2. ADD MODE LOGIC
  IF P_TRNMODE = 'ADD' THEN
    
    -- Case A: Updating an existing PENDING transaction
    IF NVL(P_SYSTRNNO, 0) != 0 THEN
      SELECT TRNSTATUS INTO V_TRNSTATUS FROM SAHIL_MSTUSERPROFILETRANS WHERE SYSTRNNO = P_SYSTRNNO;
      
      IF V_TRNSTATUS = 'P' THEN
        UPDATE SAHIL_MSTUSERPROFILETRANS
        SET USERID    = P_USERID, 
            FULLNAME  = P_FULLNAME, 
            EMAIL     = P_EMAIL,
            PASSWORD  = P_PASSWORD,
            AGE       = P_AGE,
            PHONE     = P_PHONE,
            GENDER    = P_GENDER,
            ADDRESS   = P_ADDRESS,
            CITY      = P_CITY,
            STATE     = P_STATE,
            ZIPCODE   = P_ZIPCODE,
            LUPDNUSER = P_CREATEDBY,     -- Update "Last Updated By"
            LUPDNDT   = CURRENT_TIMESTAMP -- Update "Last Updated At"
        WHERE SYSTRNNO = P_SYSTRNNO;     -- Fixed typo here

        OPEN P_CUROUTPUT FOR SELECT '1' AS FLAG, 'Pending ADD record updated.' AS MSG FROM DUAL;
      ELSE
        OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'Record is already processed (Authorized/Rejected).' AS MSG FROM DUAL;
      END IF;

    -- Case B: New ADD Entry
    ELSE
      -- Check if already pending in Trans Table to avoid duplicates
      SELECT COUNT(*) INTO V_CNT FROM SAHIL_MSTUSERPROFILETRANS WHERE (USERID = P_USERID OR EMAIL = P_EMAIL) AND TRNSTATUS = 'P';
      
      IF V_CNT > 0 THEN
         OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'A transaction for this user is already pending approval.' AS MSG FROM DUAL;
         RETURN;
      END IF;

      INSERT INTO SAHIL_MSTUSERPROFILETRANS (
        SYSTRNNO, MSYSTRNNO, SYSUSERNO, TRNID, TRNMODE, TRNSTATUS, 
        CREATEDBY, CREATEDDT, LUPDNUSER, LUPDNDT, USERID, FULLNAME, EMAIL, 
        PASSWORD, AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE
      ) VALUES (
        SAHIL_MSTUSERPROFILETRANS_SEQ.NEXTVAL, 0, 0, 'N', 'ADD', 'P', 
        P_CREATEDBY, CURRENT_TIMESTAMP, P_CREATEDBY, CURRENT_TIMESTAMP,
        P_USERID, P_FULLNAME, P_EMAIL, P_PASSWORD, 
        P_AGE, P_PHONE, P_GENDER, P_ADDRESS, P_CITY, P_STATE, P_ZIPCODE
      );

      OPEN P_CUROUTPUT FOR SELECT '1' AS FLAG, 'Record saved for approval.' AS MSG FROM DUAL;
    END IF;

  -- 3. EDIT MODE LOGIC
  ELSIF P_TRNMODE = 'EDIT' THEN
    IF NVL(P_SYSUSERNO, 0) != 0 THEN
      
      -- Check if an edit for this specific user is already pending
      SELECT COUNT(*) INTO V_CNT FROM SAHIL_MSTUSERPROFILETRANS WHERE SYSUSERNO = P_SYSUSERNO AND TRNSTATUS = 'P';
      
      IF V_CNT > 0 THEN
        OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'An edit for this user is already pending approval.' AS MSG FROM DUAL;
        RETURN;
      END IF;

      INSERT INTO SAHIL_MSTUSERPROFILETRANS (
        SYSTRNNO, MSYSTRNNO, SYSUSERNO, TRNID, TRNMODE, TRNSTATUS, 
        CREATEDBY, CREATEDDT, LUPDNUSER, LUPDNDT, USERID, FULLNAME, EMAIL, 
        PASSWORD, AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE
      ) VALUES (
        SAHIL_MSTUSERPROFILETRANS_SEQ.NEXTVAL, 0, P_SYSUSERNO, 'N', 'EDIT', 'P', 
        P_CREATEDBY, CURRENT_TIMESTAMP, P_CREATEDBY, CURRENT_TIMESTAMP,
        P_USERID, P_FULLNAME, P_EMAIL, P_PASSWORD, 
        P_AGE, P_PHONE, P_GENDER, P_ADDRESS, P_CITY, P_STATE, P_ZIPCODE
      );

      OPEN P_CUROUTPUT FOR SELECT '1' AS FLAG, 'Edit request sent for approval.' AS MSG FROM DUAL;
    ELSE
      OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'Master System User No is required for Edit.' AS MSG FROM DUAL;
    END IF;

  ELSE
    OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'Invalid Mode (Use ADD/EDIT).' AS MSG FROM DUAL;
  END IF;

  COMMIT; -- Use carefully based on your app architecture

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    OPEN P_CUROUTPUT FOR 
    SELECT '0' AS FLAG, 'System Error: ' AS MSG FROM DUAL;
END;
/





































-- AUTH (CHECKER SP) FOR MAIN TABLE SAHIL_MSTUSERPROFILE
CREATE OR REPLACE PROCEDURE SAHIL_USP_AUTHORISE_USERPROFILE
(
  P_SYSTRNNO      IN NUMBER,
  P_TRNSTATUS     IN VARCHAR2,   -- 'A' for Authorize, 'R' for Reject
  P_REJECTREMARK  IN VARCHAR2,
  P_AUTHORISEDBY  IN VARCHAR2,
  P_CUROUTPUT     OUT SYS_REFCURSOR
)
AS
  V_CNT         NUMBER := 0;
  V_TRNMODE     VARCHAR2(10);
  V_SYSUSERNO   NUMBER;
  V_CREATEDBY   VARCHAR2(50);
  V_NEW_USERNO  NUMBER;
BEGIN
  -- 1. Fetch record details and check existence in one go
  BEGIN
    SELECT TRNMODE, SYSUSERNO, CREATEDBY
    INTO V_TRNMODE, V_SYSUSERNO, V_CREATEDBY
    FROM SAHIL_MSTUSERPROFILETRANS
    WHERE SYSTRNNO = P_SYSTRNNO 
      AND TRNSTATUS = 'P'; -- Only process pending records
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'No pending record found with this ID.' AS MSG FROM DUAL;
      RETURN;
  END;

  -- 2. Maker/Checker Validation
  IF V_CREATEDBY = P_AUTHORISEDBY THEN
    OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'Maker cannot approve their own request.' AS MSG FROM DUAL;
    RETURN;
  END IF;

  -- 3. REJECTION LOGIC
  IF P_TRNSTATUS = 'R' THEN
    IF P_REJECTREMARK IS NULL THEN
      OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'Please provide a rejection reason.' AS MSG FROM DUAL;
      RETURN;
    END IF;

    UPDATE SAHIL_MSTUSERPROFILETRANS
    SET TRNSTATUS    = 'R',
        REJECTREMARK = P_REJECTREMARK,
        AUTHORISEDBY = P_AUTHORISEDBY,
        AUTHORISEDON = CURRENT_TIMESTAMP
    WHERE SYSTRNNO   = P_SYSTRNNO;

    OPEN P_CUROUTPUT FOR SELECT '1' AS FLAG, 'Request rejected successfully.' AS MSG FROM DUAL;
    COMMIT;
    RETURN;
  END IF;

  -- 4. APPROVAL LOGIC (P_TRNSTATUS = 'A')
  IF V_TRNMODE = 'ADD' THEN
    -- Get next sequence value for the Main Table
    V_NEW_USERNO := SAHIL_MSTUSERPROFILE_SEQ.NEXTVAL;

    INSERT INTO SAHIL_MSTUSERPROFILE (
      SYSUSERNO, USERID, FULLNAME, EMAIL, PASSWORD,
      AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE,
      CREATEDBY, CREATEDDT, LUPDNUSER, LUPDNDT
    )
    SELECT
      V_NEW_USERNO, USERID, FULLNAME, EMAIL, PASSWORD,
      AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE,
      CREATEDBY, CREATEDDT, LUPDNUSER, LUPDNDT
    FROM SAHIL_MSTUSERPROFILETRANS
    WHERE SYSTRNNO = P_SYSTRNNO;

    -- Link the Trans table to the newly created Master ID
    UPDATE SAHIL_MSTUSERPROFILETRANS
    SET SYSUSERNO = V_NEW_USERNO
    WHERE SYSTRNNO = P_SYSTRNNO;

  ELSIF V_TRNMODE = 'EDIT' THEN
    UPDATE SAHIL_MSTUSERPROFILE M
    SET (USERID, FULLNAME, EMAIL, PASSWORD, AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE, LUPDNUSER, LUPDNDT) =
        (SELECT USERID, FULLNAME, EMAIL, PASSWORD, AGE, PHONE, GENDER, ADDRESS, CITY, STATE, ZIPCODE, P_AUTHORISEDBY, CURRENT_TIMESTAMP
         FROM SAHIL_MSTUSERPROFILETRANS
         WHERE SYSTRNNO = P_SYSTRNNO)
    WHERE SYSUSERNO = V_SYSUSERNO;
  END IF;

  -- 5. Finalize Transaction Table Status
  UPDATE SAHIL_MSTUSERPROFILETRANS
  SET TRNSTATUS    = 'A',
      AUTHORISEDBY = P_AUTHORISEDBY,
      AUTHORISEDON = CURRENT_TIMESTAMP
  WHERE SYSTRNNO   = P_SYSTRNNO;

  OPEN P_CUROUTPUT FOR SELECT '1' AS FLAG, 'Request approved and Master updated.' AS MSG FROM DUAL;
  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    OPEN P_CUROUTPUT FOR SELECT '0' AS FLAG, 'Error: 'AS MSG FROM DUAL;
END;
/
