create or replace PROCEDURE "USP_SAVE_PULL_CONNECTIONS" 
( 
 P_SYSCONNOTRN      NUMBER,
 P_MYSYSCONNOTRN    NUMBER,
 P_TRNMODE          VARCHAR2,
 P_DBTYPE           VARCHAR2,
 P_SERVERNAME       VARCHAR2,
 P_TNSDBNAME        VARCHAR2,
 P_USERID           VARCHAR2,
 P_PASSWORD         VARCHAR2,
 P_CREATEDBY        VARCHAR2,
 P_CREATEDDT        DATE,
 P_LUPDNUSER        VARCHAR2,
 P_LUPDNDT          DATE,
 P_CONNECTIONDESC   VARCHAR2,
 P_CUROUTPUT        OUT SYS_REFCURSOR
) 
AS
 V_ERROR_MSG              VARCHAR2(1000); 
 V_COUNT                  NUMBER(10);
 V_RECORDSTATUS           VARCHAR2(2); 
 V_SYSCONNOTRN            NUMBER(10,0) := 0;
 V_ERROR                  NUMBER(10,0)  := 0;
 V_DUP_COUNT              NUMBER(10, 0) := 0;
BEGIN

IF P_TRNMODE = 'ADD' THEN
  SELECT COUNT(1) 
      INTO   V_DUP_COUNT
      FROM   PULL_CONNECTIONSTRANS 
      WHERE  CONNECTIONDESC = P_CONNECTIONDESC
      AND    TRNSTATUS IN ('P', 'A'); 

      IF V_DUP_COUNT = 0 THEN
        INSERT INTO PULL_CONNECTIONSTRANS(MSYSCONNOTRN, SYSCONNO, TRNID, TRNMODE, 
                                          DBTYPE, SERVERNAME, TNSDBNAME, USERID, PASSWORD, 
                                           TRNSTATUS,
                                          CREATEDBY, CREATEDDT, LUPDNUSER, LUPDNDT,
                                          CONNECTIONDESC)
                                   VALUES(0, 0, 'N', P_TRNMODE, P_DBTYPE, P_SERVERNAME, P_TNSDBNAME, P_USERID, ENCRYPT_DATA(P_PASSWORD),
                                           'P', P_CREATEDBY, P_CREATEDDT, P_LUPDNUSER, P_LUPDNDT, 
                                          P_CONNECTIONDESC);

        COMMIT;
        V_ERROR_MSG := 'RECORD SAVED SUCCESSFULLY'; 
        OPEN P_CUROUTPUT FOR SELECT '1' "FLAG" , V_ERROR_MSG "ERROR_MSG" FROM DUAL;   
        RETURN;
      ELSE
        V_ERROR_MSG := 'PULL CONNECTION : '''||P_CONNECTIONDESC||''' ALREADY EXSITS'; 
        OPEN P_CUROUTPUT FOR SELECT '0' "FLAG" , V_ERROR_MSG "ERROR_MSG" FROM DUAL;   
        RETURN;
      END IF;
ELSIF P_TRNMODE = 'UPDATE' THEN
      UPDATE PULL_CONNECTIONSTRANS
      SET    DBTYPE         = P_DBTYPE, 
             SERVERNAME     = P_SERVERNAME, 
             TNSDBNAME      = P_TNSDBNAME, 
             USERID         = P_USERID, 
             PASSWORD       = ENCRYPT_DATA(P_PASSWORD), 
             LUPDNUSER      = P_LUPDNUSER, 
             LUPDNDT        = SYSDATE,
             CONNECTIONDESC = P_CONNECTIONDESC
      WHERE  SYSCONNOTRN    = P_SYSCONNOTRN; 

      COMMIT;

      V_ERROR_MSG := 'RECORD UPDATED SUCCESSFULLY';
      OPEN P_CUROUTPUT FOR SELECT '1' "FLAG" , V_ERROR_MSG "ERROR_MSG" FROM DUAL;   
      RETURN;
ELSIF P_TRNMODE = 'EDIT' THEN
      INSERT INTO PULL_CONNECTIONSTRANS(MSYSCONNOTRN,SYSCONNO,TRNID,TRNMODE,
                                          DBTYPE, SERVERNAME, TNSDBNAME, USERID, PASSWORD, 
                                           TRNSTATUS,
                                          CREATEDBY, CREATEDDT, LUPDNUSER, LUPDNDT,
                                          CONNECTIONDESC)
      SELECT 0,SYSCONNO,'N' TRNID,'EDIT' TRNMODE, P_DBTYPE, P_SERVERNAME, P_TNSDBNAME, P_USERID, ENCRYPT_DATA(P_PASSWORD),
              'P' TRNSTATUS, P_CREATEDBY, P_CREATEDDT, P_LUPDNUSER, P_LUPDNDT, P_CONNECTIONDESC
      FROM   PULL_CONNECTIONS
      WHERE  SYSCONNO   = P_SYSCONNOTRN;
      --AND    MSYSCONNOTRN = P_MYSYSCONNOTRN
      --AND    TRNID = 'N';

      SELECT PULL_CONNECTIONSTRANS_SEQ.CURRVAL
      INTO   V_SYSCONNOTRN
      FROM   DUAL;

      UPDATE PULL_CONNECTIONSTRANS
      SET    MSYSCONNOTRN = V_SYSCONNOTRN
      WHERE  SYSCONNOTRN   = V_SYSCONNOTRN;

      INSERT INTO PULL_CONNECTIONSTRANS(MSYSCONNOTRN,SYSCONNO,TRNID,TRNMODE, 
                                         DBTYPE, SERVERNAME, TNSDBNAME, USERID, PASSWORD, 
                                         TRNSTATUS,CREATEDBY,CREATEDDT,LUPDNUSER,LUPDNDT,
                                         AUTHORISEDBY,AUTHORISEDON,CONNECTIONDESC)
      SELECT V_SYSCONNOTRN,SYSCONNO,'O' TRNID,'EDIT' TRNMODE, 
             DBTYPE, SERVERNAME, TNSDBNAME, USERID, PASSWORD,'A' TRNSTATUS,
             CREATEDBY,CREATEDDT,LUPDNUSER,LUPDNDT,AUTHORISEDBY,AUTHORISEDON,CONNECTIONDESC
      FROM   PULL_CONNECTIONS
      WHERE  SYSCONNO      = P_SYSCONNOTRN;
      --AND    MSYSCONNOTRN = P_MYSYSCONNOTRN
      --AND    TRNID = 'N';

      COMMIT;
        
       PRC_ERRORLOG('USP_AUTH_PULL_CONNECTIONS', '1 called ',V_SYSCONNOTRN);
       USP_AUTH_PULL_CONNECTIONS(V_SYSCONNOTRN,'A','',P_USERID,P_CUROUTPUT);

      V_ERROR_MSG := 'RECORD UPDATED SUCCESSFULLY';
      OPEN P_CUROUTPUT FOR SELECT '1' "FLAG" , V_ERROR_MSG "ERROR_MSG" FROM DUAL;   
      RETURN;
END IF;
 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;  
    V_ERROR_MSG :=	SQLERRM||' - '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
     PRC_ERRORLOG ('USP_SAVE_PULL_CONNECTIONS', V_ERROR_MSG,' P_CONNECTIONDESC - '||P_CONNECTIONDESC,''); 
        OPEN P_CUROUTPUT FOR SELECT '0' "FLAG", 'ERROR' "ERROR_MSG" FROM DUAL; 
        RAISE_APPLICATION_ERROR(-20001,'# ERROR : ' ||V_ERROR_MSG|| ' : ' ||  DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN;
  END;
  
  
  
  
  
  -------------------------------------------
  
  
  
  
  create or replace PROCEDURE "USP_AUTH_PULL_CONNECTIONS" 
(
  P_SYSCONNOTRN  NUMBER,
  P_RECORDSTATUS VARCHAR2,
  P_REJECTREMARK VARCHAR2,
  P_USERID       VARCHAR2,
  P_CUROUTPUT    OUT SYS_REFCURSOR
)
AS
  V_MESSAGE   VARCHAR2(500) := '';
  V_TRANMODE  VARCHAR2(4 BYTE) := ' ';
  V_SYSCONNO  NUMBER(10,0) := 0;
  V_CNT       NUMBER(10,0) := 0;
  V_FILEDATE    DATE := SYSDATE;
  V_CURSTSTUD VARCHAR2(1000 BYTE);
--  PRAGMA AUTONOMOUS_TRANSACTION;


BEGIN

  IF P_RECORDSTATUS = 'R' AND (P_REJECTREMARK = '' OR P_REJECTREMARK IS NULL) THEN
    V_MESSAGE := 'REASON FOR REJECTION CANNOT BE BLANK'; 
    OPEN P_CUROUTPUT FOR SELECT '1' "FLAG" , V_MESSAGE "ERROR_MSG" FROM DUAL;   
    RETURN;
  END IF;

  PRC_STEPLOG('USP_AUTH_PULL_CONNECTIONS', '1 BLOCK TRANS',SQL%ROWCOUNT);

  IF V_MESSAGE = '' OR V_MESSAGE IS NULL THEN
    UPDATE PULL_CONNECTIONSTRANS
    SET    MSYSCONNOTRN = P_SYSCONNOTRN,
           TRNSTATUS  = P_RECORDSTATUS,
           REJECTREMARK  = P_REJECTREMARK,
           AUTHORISEDBY  = P_USERID,
           AUTHORISEDON  = SYSDATE,
           LUPDNUSER     = P_USERID,
           LUPDNDT       = SYSDATE
    WHERE  SYSCONNOTRN   = P_SYSCONNOTRN
    AND    TRNSTATUS  = 'P';

    PRC_STEPLOG('USP_AUTH_PULL_CONNECTIONS', '2 BLOCK TRANS',SQL%ROWCOUNT);

    IF P_RECORDSTATUS = 'A' THEN
      UPDATE PULL_CONNECTIONS M
      SET   (M.DBTYPE, M.SERVERNAME, M.TNSDBNAME, M.USERID, M.PASSWORD,
             M.LUPDNUSER,M.LUPDNDT,M.AUTHORISEDBY,M.AUTHORISEDON, M.CONNECTIONDESC) =
            (SELECT T.DBTYPE, T.SERVERNAME, T.TNSDBNAME, T.USERID, T.PASSWORD,
                    T.LUPDNUSER,T.LUPDNDT,T.AUTHORISEDBY,T.AUTHORISEDON, T.CONNECTIONDESC
             FROM   PULL_CONNECTIONSTRANS T
             WHERE  M.SYSCONNO = T.SYSCONNO
             AND    T.SYSCONNOTRN = P_SYSCONNOTRN
             AND    T.SYSCONNO <> 0
             AND    T.TRNID = 'N'
             AND    T.TRNMODE = 'EDIT')
             WHERE  M.SYSCONNO
             IN     (SELECT SYSCONNO
                     FROM   PULL_CONNECTIONSTRANS
                     WHERE  SYSCONNOTRN  = P_SYSCONNOTRN
                     AND    SYSCONNO = M.SYSCONNO
                     AND    SYSCONNO <> 0
                     AND    TRNID     = 'N'
                     AND    TRNMODE   = 'EDIT');

     PRC_STEPLOG('USP_AUTH_PULL_CONNECTIONS', '3 BLOCK TRANS',SQL%ROWCOUNT);    

      INSERT INTO PULL_CONNECTIONS(DBTYPE,SERVERNAME,TNSDBNAME,USERID,PASSWORD,
                                   STATUS,CREATEDBY,CREATEDDT,LUPDNUSER,LUPDNDT,
                                   AUTHORISEDBY,AUTHORISEDON,CONNECTIONDESC)
      SELECT DBTYPE,SERVERNAME,TNSDBNAME,USERID,PASSWORD,
             TRNSTATUS,CREATEDBY,CREATEDDT,LUPDNUSER,LUPDNDT,P_USERID,SYSDATE,CONNECTIONDESC
      FROM   PULL_CONNECTIONSTRANS
      WHERE  SYSCONNOTRN = P_SYSCONNOTRN
      AND    SYSCONNO = 0
      AND    TRNID = 'N'
      AND    TRNMODE = 'ADD';

      V_CNT := SQL%ROWCOUNT;

      IF V_CNT <> 0 THEN
        SELECT PULL_CONNECTIONS_SEQ.CURRVAL
        INTO   V_SYSCONNO 
        FROM   DUAL;
      END IF;

     PRC_STEPLOG('USP_AUTH_PULL_CONNECTIONS', '4 BLOCK TRANS',SQL%ROWCOUNT);

      UPDATE PULL_CONNECTIONSTRANS
      SET    SYSCONNO = V_SYSCONNO
      WHERE  SYSCONNOTRN = P_SYSCONNOTRN
      AND    SYSCONNO = 0
      AND    TRNID = 'N'
      AND    TRNMODE = 'ADD';

      COMMIT;
      V_MESSAGE := 'RECORD AUTHORISED SUCCESSFULLY';
      OPEN P_CUROUTPUT FOR SELECT '1' "FLAG" , V_MESSAGE "ERROR_MSG" FROM DUAL;   
      RETURN;

    ELSIF P_RECORDSTATUS = 'R' THEN
      V_MESSAGE := 'RECORD REJECTED SUCCESSFULLY';  
      OPEN P_CUROUTPUT FOR SELECT '1' "FLAG" , V_MESSAGE "ERROR_MSG" FROM DUAL;   
      RETURN;
    END IF;  



    END IF;

  EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;  
    V_MESSAGE :=	SQLERRM||' - '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
     PRC_ERRORLOG ('USP_AUTH_PULL_CONNECTIONS', V_MESSAGE,' P_SYSCONNOTRN - '||P_SYSCONNOTRN,''); 
        OPEN P_CUROUTPUT FOR SELECT '0' "FLAG", 'ERROR' "ERROR_MSG" FROM DUAL; 
        RAISE_APPLICATION_ERROR(-20001,'# ERROR : ' ||V_MESSAGE|| ' : ' ||  DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN;
  END;