create or replace PROCEDURE "USP_AUTH_EODBALANCE" (

P_RECOTYPECD      VARCHAR2,
P_RECON_SCOPE     VARCHAR2,
P_SYSTRNNO        VARCHAR2,
P_ACTION          VARCHAR2,
P_USERID          VARCHAR2,
P_REJECT_REASON   VARCHAR2,
P_CURSOR     OUT SYS_REFCURSOR

) AS

  V_TRNMODE        VARCHAR2 (5)   := '' ;
  V_MESSAGE        VARCHAR2(2000) := '' ;
  V_SYSBALNO       VARCHAR2(500)        ;
  VALIDATION_ERROR EXCEPTION            ;
  PRAGMA EXCEPTION_INIT( VALIDATION_ERROR, -20001 );

BEGIN

  EXECUTE IMMEDIATE 'TRUNCATE TABLE GTT_MATCH';

  INSERT INTO GTT_MATCH (SYSTRNNO)
  SELECT TRIM(REGEXP_SUBSTR(P_SYSTRNNO, '[^,]+', 1, LEVEL)) AS SYSTRNNO
  FROM DUAL
  CONNECT BY REGEXP_SUBSTR(P_SYSTRNNO, '[^,]+', 1, LEVEL) IS NOT NULL;

-- AUTHORIZATION
  IF(P_ACTION = 'A') THEN
     FOR I IN ( SELECT * FROM DTB_EODBALANCE_TRANS 
                WHERE   SYSTRNNO IN ( SELECT SYSTRNNO FROM GTT_MATCH )
                AND     RECORDSTATUS = '01' )
     LOOP

    IF NVL( I.SYSTRNNO, 0 ) = 0 THEN
       V_MESSAGE := 'PK cannot be null';
       RAISE VALIDATION_ERROR;
    END IF;

     IF I.TRANMODE = 'ADD' THEN
        V_SYSBALNO := DTB_EODBALANCE_SEQ.NEXTVAL;

        INSERT INTO DTB_EODBALANCE 
               ( SYSBALNO, RECOTYPECD, RECON_SCOPE, FILEDATE, ACCNO, 
                  BALANCEAMT, RECORDSTATUS, CREATEDBY, CREATEDDT, 
                  LSTUPDBY, LSTUPDDT, MSYSTRNNO )
        VALUES ( V_SYSBALNO, P_RECOTYPECD, P_RECON_SCOPE, I.FILEDATE, I.ACCNO,
                 I.BALANCEAMT, '10', I.CREATEDBY, I.CREATEDDT, 
                 I.LSTUPDBY, I.LSTUPDDT, I.SYSTRNNO );
     END IF;

     IF I.TRANMODE = 'EDIT' THEN
        UPDATE DTB_EODBALANCE 
        SET    ACCNO = I.ACCNO, BALANCEAMT = I.BALANCEAMT, RECORDSTATUS = '10'
        WHERE  SYSBALNO = I.SYSBALNO;
--DBMS_OUTPUT.PUT_LINE(I.TRANMODE);
     END IF;

     UPDATE DTB_EODBALANCE_TRANS 
     SET    RECORDSTATUS = '10', AUTHORISEDBY = P_USERID, SYSBALNO = DECODE(I.TRANMODE,'ADD',V_SYSBALNO,'EDIT',I.SYSBALNO),
            AUTHORISEDON = SYSDATE, STATUS = 'A'
     WHERE  SYSTRNNO = I.SYSTRNNO;

     END LOOP;

     OPEN   P_CURSOR FOR
     SELECT 1 "FLAG" , 'RECORD SUCCESSFULLY AUTHORIZED' "ERROR_MSG" FROM DUAL ;

  END IF;

  IF ( P_ACTION = 'R' ) THEN 

     FOR I IN ( SELECT * FROM DTB_EODBALANCE_TRANS 
                WHERE   SYSTRNNO IN ( SELECT SYSTRNNO FROM GTT_MATCH )
                AND     RECORDSTATUS = '01' )
     LOOP

     IF NVL( I.SYSTRNNO, 0 ) = 0 THEN
       V_MESSAGE := 'PK cannot be null';
       RAISE VALIDATION_ERROR;
     END IF;

     IF P_REJECT_REASON IS NULL THEN
       V_MESSAGE := 'Reject reason cannot be blank';
       RAISE VALIDATION_ERROR;
     END IF;

     IF I.TRANMODE = 'ADD' THEN
      UPDATE DTB_EODBALANCE_TRANS SET RECORDSTATUS = '20', REJECTREMARK = P_REJECT_REASON
      WHERE  SYSTRNNO = I.SYSTRNNO;
     END IF;

     IF I.TRANMODE = 'EDIT' THEN
        UPDATE DTB_EODBALANCE_TRANS SET RECORDSTATUS = '20', REJECTREMARK = P_REJECT_REASON,
               STATUS = 'R'
        WHERE  SYSTRNNO = I.SYSTRNNO;

        UPDATE DTB_EODBALANCE SET RECORDSTATUS = '10'
        WHERE  SYSBALNO = I.SYSBALNO;
     END IF;

     END LOOP;

     OPEN   P_CURSOR FOR
     SELECT 1 "FLAG" , 'RECORD REJECTED SUCCESSFULLY' "ERROR_MSG" FROM DUAL ;
  END IF;

COMMIT;

EXCEPTION 
WHEN VALIDATION_ERROR THEN

   ROLLBACK; 

   PRC_ERRORLOG ('USP_AUTH_EODBALANCE', V_MESSAGE,'SYSTRNNO - '||P_SYSTRNNO  );

    OPEN P_CURSOR FOR
    SELECT 0 "FLAG" , V_MESSAGE "ERROR_MSG" FROM DUAL;

   COMMIT;

   RETURN;

WHEN OTHERS THEN

   ROLLBACK; 

   V_MESSAGE := SQLERRM||' - '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

  PRC_ERRORLOG ('USP_AUTH_EODBALANCE', V_MESSAGE ,'SYSTRNNO - '||P_SYSTRNNO );

    OPEN P_CURSOR FOR
    SELECT 0 "FLAG" , V_MESSAGE "ERROR_MSG" FROM DUAL;

   COMMIT;
   RETURN;

END;