create or replace PROCEDURE "USP_SAVE_EOD_BALANCE" 
(

P_RECOTYPECD  VARCHAR2,
P_RECON_SCOPE VARCHAR2,
P_USERID      VARCHAR2,
P_CLOB        CLOB,
P_FILEDATE    DATE,
P_CUROUTPUT   OUT SYS_REFCURSOR

) AS

V_DESCRIPTION  VARCHAR2(4000);
V_ACCOUNTNO    VARCHAR2(4000);
V_BALANCE      NUMBER(20,2);
V_SYSTRNNO     NUMBER(20);
V_SYSBALNO     NUMBER(20);
V_ERROR_MSG    VARCHAR2(4000);
V_SYSDATE      TIMESTAMP := SYSDATE;
V_TRNMODE      VARCHAR2(100);
V_COUNT        VARCHAR2(100);

 VALIDATION_ERROR EXCEPTION;
 PRAGMA EXCEPTION_INIT( VALIDATION_ERROR, -20001 );

BEGIN


  FOR I IN ( SELECT DESCRIPTION, ACCOUNTNO, BALANCE, SYSBALNO, SYSTRNNO
     FROM   DUAL, JSON_TABLE( P_CLOB, '$'
     COLUMNS ( NESTED PATH '$.EODDETAILS[*]'
     COLUMNS ( DESCRIPTION VARCHAR2(1000) PATH '$.DESCRIPTION',
               ACCOUNTNO VARCHAR2(500) PATH '$.ACCOUNTNO',
               BALANCE NUMBER(20,2) PATH '$.BALANCE',
               SYSBALNO NUMBER PATH '$.SYSBALNO',
               SYSTRNNO NUMBER PATH '$.SYSTRNNO'))) AS JT 
     WHERE     BALANCE IS NOT NULL ) 
  LOOP
  DBMS_OUTPUT.PUT_LINE('LOOP --');
     V_DESCRIPTION  :=  I.DESCRIPTION ; DBMS_OUTPUT.PUT_LINE(V_DESCRIPTION);
     V_ACCOUNTNO    :=  I.ACCOUNTNO   ; DBMS_OUTPUT.PUT_LINE(V_ACCOUNTNO);
     V_BALANCE      :=  I.BALANCE     ; DBMS_OUTPUT.PUT_LINE(V_BALANCE);
     V_SYSBALNO     :=  I.SYSBALNO    ; DBMS_OUTPUT.PUT_LINE(V_SYSBALNO);
     V_SYSTRNNO     :=  I.SYSTRNNO    ; DBMS_OUTPUT.PUT_LINE(V_SYSTRNNO);


  IF ( V_ACCOUNTNO IS NULL OR V_ACCOUNTNO = '' ) THEN
     V_ERROR_MSG :=  'Account No. cannot be null' ;
     RAISE VALIDATION_ERROR;
  END IF;

  IF ( V_BALANCE IS NULL ) THEN
     V_ERROR_MSG :=  'Balance Amount cannot be null' ;
     RAISE VALIDATION_ERROR;
  END IF;

  IF V_SYSTRNNO IS NULL THEN 
     V_TRNMODE := 'ADD';
  ELSE 
     V_TRNMODE := 'EDIT';
  END IF ;

  IF V_TRNMODE = 'EDIT' THEN
     DBMS_OUTPUT.PUT_LINE(V_TRNMODE);

     SELECT COUNT(*) INTO V_COUNT
     FROM   DTB_EODBALANCE_TRANS
     WHERE  TRANMODE = 'EDIT' AND ACCNO = V_ACCOUNTNO AND FILEDATE = P_FILEDATE
     AND    RECON_SCOPE = P_RECON_SCOPE AND RECOTYPECD = P_RECOTYPECD
     AND    RECORDSTATUS = '01';

     IF V_COUNT > 0 THEN
        V_ERROR_MSG := 'PENDING FOR AUTHORIZATION FOR ACCOUNTNO'||V_ACCOUNTNO;
        RAISE VALIDATION_ERROR;
     END IF;

     INSERT INTO DTB_EODBALANCE_TRANS
            ( SYSTRNNO, MSYSTRNNO, TRANMODE, SYSBALNO, RECOTYPECD, 
              RECON_SCOPE, ACCNO, BALANCEAMT, STATUS, RECORDSTATUS, 
              CREATEDBY, CREATEDDT, LSTUPDBY, LSTUPDDT, FILEDATE )
     SELECT   DTB_EODBALANCE_TRANS_SEQ.NEXTVAL, MSYSTRNNO, V_TRNMODE, SYSBALNO, RECOTYPECD, 
              RECON_SCOPE, V_ACCOUNTNO, V_BALANCE, 'P', '01', 
              CREATEDBY, CREATEDDT, LSTUPDBY, LSTUPDDT, P_FILEDATE 
     FROM     DTB_EODBALANCE WHERE SYSBALNO = V_SYSBALNO ;

     UPDATE   DTB_EODBALANCE SET RECORDSTATUS = '01'
     WHERE    SYSBALNO = V_SYSBALNO ;    

  END IF;

  IF V_TRNMODE = 'ADD' THEN
     DBMS_OUTPUT.PUT_LINE(V_TRNMODE);
     SELECT COUNT(*) INTO V_COUNT
     FROM   DTB_EODBALANCE_TRANS
     WHERE  TRANMODE = 'ADD' AND ACCNO = V_ACCOUNTNO AND FILEDATE = P_FILEDATE
     AND    RECON_SCOPE = P_RECON_SCOPE AND RECOTYPECD = P_RECOTYPECD
     AND    RECORDSTATUS = '01';

     IF V_COUNT > 0 THEN
        V_ERROR_MSG := 'PENDING FOR AUTHORIZATION FOR ACCOUNTNO'||V_ACCOUNTNO;
        RAISE VALIDATION_ERROR;
     END IF;

     INSERT INTO DTB_EODBALANCE_TRANS 
            ( SYSTRNNO, TRANMODE, SYSBALNO, RECOTYPECD, 
              RECON_SCOPE, ACCNO, BALANCEAMT, STATUS, RECORDSTATUS, 
              CREATEDBY, CREATEDDT, LSTUPDBY, LSTUPDDT, FILEDATE  )
     SELECT   DTB_EODBALANCE_TRANS_SEQ.NEXTVAL , V_TRNMODE, 0, P_RECOTYPECD,
              P_RECON_SCOPE, JT.ACCOUNTNO, JT.BALANCE, 'P', '01',
              P_USERID, V_SYSDATE, P_USERID, V_SYSDATE, P_FILEDATE 
       FROM   DUAL, JSON_TABLE( P_CLOB, '$'
     COLUMNS ( NESTED PATH '$.EODDETAILS[*]'
     COLUMNS ( DESCRIPTION VARCHAR2(1000) PATH '$.DESCRIPTION',
               ACCOUNTNO VARCHAR2(500) PATH '$.ACCOUNTNO',
               BALANCE NUMBER(20,2) PATH '$.BALANCE',
               SYSBALNO NUMBER PATH '$.SYSBALNO',
               SYSTRNNO NUMBER PATH '$.SYSTRNNO'))) AS JT 
      WHERE    JT.SYSTRNNO IS NULL AND ACCOUNTNO = V_ACCOUNTNO;

  END IF;

  END LOOP;

  V_ERROR_MSG := 'Record Saved Successfully' ;

  PRC_ERRORLOG ( 'USP_SAVE_EOD_BALANCE', V_ERROR_MSG , 'CLOB', P_CLOB ) ;

   COMMIT ; 

  OPEN P_CUROUTPUT FOR
  SELECT 1 FLAG , V_ERROR_MSG ERROR_MSG FROM DUAL ;

EXCEPTION 

WHEN VALIDATION_ERROR THEN

   ROLLBACK; 

   PRC_ERRORLOG ('USP_SAVE_EOD_BALANCE', V_ERROR_MSG ,'');

    OPEN P_CUROUTPUT FOR
    SELECT 0 FLAG , V_ERROR_MSG ERROR_MSG FROM DUAL ;

   COMMIT ;

   RETURN ;

WHEN OTHERS THEN

   ROLLBACK ; 

   V_ERROR_MSG := SQLERRM||' - '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

   PRC_ERRORLOG ('USP_SAVE_EOD_BALANCE', V_ERROR_MSG ,P_CLOB) ;

    OPEN P_CUROUTPUT FOR
    SELECT 0 FLAG , V_ERROR_MSG ERROR_MSG FROM DUAL ;

   COMMIT ;
   RETURN ;

END;